#!/usr/bin/perl
sub by_number{
  if($a < $b) {
    1
  } elsif($a > $b) {
    -1
  } else {
    0
  }
}

my @array = qw /1 3 5 7 9/;
my @result = sort by_number @array;
print "The result is [@result]\n";

