#!/usr/bin/perl
#将哈希姓名表中的元素，先按姓氏以字母顺序排序（不区分大小写），若姓氏相同再按名字的字母顺序排列（不区分大小写）
my %last_name = qw {fred flintstone Wilma Flintstone Barney Rubble betty rubble Bamm-Bamm Rubble PEBBLES FLINTSTONE};

sub by_family_and_name{
	"\L$last_name{$a}" cmp "\L$last_name{$b}" or
	"\L$a" cmp "\L$b"
}

foreach (sort by_family_and_name keys %last_name){
	printf "%-10s %-10s\n", $_, $last_name{$_};
}

