#!/usr/bin/perl
#在输入的字符串中查找子串的位置
print "Please input a string: ";
chomp (my $input = <STDIN>);
print "Please input a substring: ";
chomp (my $sub = <STDIN>);

my @positions;
{
	my $pos = -1;
	while(1){
		$pos = index ($input, $sub, ++$pos);
		last if $pos < 0;
		push @positions, $pos;
	}
}
if(@positions){
	print "Found '$sub' in '$input' at [".(join ',',@positions)."]\n";
}else{
	print "Never found '$sub' in '$input'\n";
}

