#! /usr/bin/perl
#给定一个包含数字的列表，子程序above_average返回其中大于平均值的数字
use 5.010;
use strict;

sub average{
    my $total = 0;
    foreach (@_){
        $total += $_;
    }
    return $total / @_;
}

sub above_average{
    my $average = average(@_);
    my @result;
    foreach(@_){
        if($_ > $average){
            push @result, $_;
        }
    }
    return @result;
}

my @fred = above_average(1 .. 10);
print "\@fred is @fred\n";
print "(Should be 6 7 8 9 10)\n";
my @barney = above_average(100, 1..10);
print "\@barney is @barney\n";
print "(Should be just 100)\n";



