#! /usr/bin/perl -w
#使用子程序total计算1到1000的总和
use 5.010;
use strict;
sub total{
    my $total = 0;
    foreach (@_){
        $total += $_;
    }
    return $total;
}

our $total = total(1 .. 1000);
print "The total of numbers from 1 to 1000 is $total\n";
