#!/usr/bin/perl
#模仿mv命令的功能，将命令行第一个参数指定的文件变更为第二个参数的名字
use File::Basename;
use File::Spec;
if(@ARGV != 2){
	die "Usage: ex13-5 file_name new_file_name";
}
my ($source, $dest)  = @ARGV;

#判断目标路径是不是目录
if(-d $dest){
	my $basename = basename $source;
	$dest = File::Spec->catfile($dest, $basename);
}
rename $source, $dest or die "mv file '$source' to '$dest' failed: $!\n";

