#! /usr/bin/perl
#读取输入的圆半径，计算圆周长
# The circumference of circule with radius that user type into
print "Please type in radius:\n";
$radius=<STDIN>;
$pi=3.141592654;
$circumference=2*$pi*$radius;
print "The circumference of circule with radius $radius is $circumference \n";
