#! /usr/bin/perl
# The circumference of circule with radius that user types into
# If user types into a negative number, return 0 rather than negative result
print "Please type in radius:";
chomp($radius=<STDIN>);
$pi=3.141592654;
$circumference=2*$pi*$radius;
if($radius > 0){
	print "The circumference of circule with radius $radius is $circumference \n";
} else{
	print "0\n";
}
