#!/usr/bin/perl
# 分析输入文件中的单词
while(<>){  #钻石操作符逐行读取命令行中的参数并放入$_
   foreach (split) { #使用split的默认行为将$_分成空格隔开的单词，然后将每一个单词赋值给$_，这里Perl会自动处理$_的重用
    $total++;
    next if(/\W/);  #如果碰到不是单词的字符，跳过之后的表达式
    $valid++;
    $count{$_}++;  # 用哈希统计每个单词出现的次数
    ## 上面的next操作符如果执行会跳到这里
    }
}

print "total things = $total, valid things = $valid.\n";
foreach $word (sort keys %count) {
    print "$word was seen $count{$word} times.\n";
}
