#!/usr/bin/perl -w
#打印%ENV中未定义的值，显示为undefined value
use strict;
$ENV{ZERO}=0;
$ENV{EMPTY}='';
$ENV{UNDEF}=undef;
my $longest = 0;
foreach my $key (keys %ENV){
	if(length($key) > $longest){
		$longest = length($key);
	}
}
foreach my $key (sort keys %ENV){
        my $display = $ENV{$key} // "(undefined value)";
	printf "%${longest}s : %s\n", $key, $display;
}	
