#!/usr/bin/perl
use 5.010;
my $reserver_user = "root";
given ( $ARGV[0] ){
  when($_ =~ /fred/i ) { print 'Name has fred in it' }
  when( /^Fred/) { print 'Name starts  with Fred' }
  when( @ARGV != 1 ){ warn "Usage: ex15-2 <YOUR_NAME>"; continue}
  when( $reserver_user eq $ARGV[0]) {print "You cannot use reserverd name\n"; continue }
  when( 'Fred' ) { print 'Name is Fred' }
  default { print "I don't see a Fred" }
}
