#!/usr/bin/perl
#修改ex15-4，额外进行奇偶判断
sub divisions {
	my $number = shift;
	my @divisors = ();
	foreach my $divisor ( 2 .. ($number / 2)){
		push @divisors , $divisor unless $number % $divisor;
	}
	return @divisors;
}
use 5.010;
if(@ARGV != 1){
	die "Usage1: ex15-4 <Number>\n";	
}

given($ARGV[0]){
	when (! /^\d+$/){ die "Usage2: ex15-4 <Number>\n"}
	my @divisors = &divisions($_);
	my @empty;
	when (@divisors ~~ @empty){ print "'$_' is prime number\n"}
	when (2 ~~ @divisors){ print "'$_' is even\n"; continue}
	when (! (2 ~~ @divisors)) {print "'$_' is odd\n"; continue}
	default {print "The divisors of '$_' are: [@divisors]\n"}
}
