#! /usr/bin/perl -w
@读入一组字符串，按照ASCII码序排序后输出
print "Please type in the strings, end as Ctrl-D\n";
@output = sort @output = <STDIN>;
print "Reverse as array:\n";
print @output;
chomp(@output);
print "Reverse as string:@output\n";
