#!/usr/bin/perl
use File::Spec;
chomp($dir = `pwd`);
$old_name = File::Spec->catfile($dir,$ARGV[0]);
$new_name = File::Spec->catfile($dir,$ARGV[1]);
rename($old_name, $new_name)
	or warn "Can't rename '$old_name' to '$new_name':$!\n";
