#!/usr/bin/perl
while(<>){
    chomp;
    if(/\b(?<word>\w*a)\b(.{0,5})/s){
        print "Matched:|$`<$&>$'|\n";
        print "'word' contains '$+{word}'\n";
        print "The second match is: '$2'\n";
    } else{
        print "No Match:|$_|\n";
    }
}

