#!/usr/bin/perl -w
#以20字符宽，向右对齐的方式回显用户输入
print "Please type into the width:\n";
chomp (my $width = <STDIN>);
print "Please type into the input:\n";
chomp (my @input = <STDIN>);
print "0123456789" x 6 . "\n"; #标尺行
$format = "%${width}s\n";
printf $format, @input;
